services:
  nginx:
    image: nginx:1.27.5-alpine
    container_name: lc_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - lovecards-network

  php-fpm:
    build: .
    container_name: Lovecards
    volumes:
      - ./:/usr/share/nginx/html
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - lovecards-network
    environment:
      - APP_DEBUG=false
      - TZ=Asia/Shanghai

  mysql:
    image: mysql:8.0
    container_name: lc_mysql
    environment:
      - MYSQL_DATABASE=lovecards
      - MYSQL_ROOT_PASSWORD=root123
      - TZ=Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_conf:/etc/mysql/conf.d
      - mysql_logs:/var/log/mysql
    networks:
      - lovecards-network

networks:
  lovecards-network:
    external: true

volumes:
  mysql_data:
    name: lovecards_mysql_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../mysql/data
  mysql_conf:
    name: lovecards_mysql_conf
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../mysql/conf
  mysql_logs:
    name: lovecards_mysql_logs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../mysql/logs